spring:
  application:
    name: eureka-server-b
server:
  port: 9001
eureka:
  instance:
    hostname: eurekaB
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.3.8:9000/eureka/,http://192.168.3.8:9002/eureka/
