spring:
  application:
    name: goods-service

server:
  port: 9007
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.8:9000/eureka

# feign日志配置目录
logging:
  level:
    com:
      wei: debug

# 数据压缩，解决传输效率
feign:
  compression:
    request:
      enabled: true
      mime-types: text/html,application/json
      min-request-size: 2048
    response:
      enabled: true

# 配置ribbon
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
