spring:
  application:
    name: eureka-server-c
server:
  port: 9002
eureka:
  instance:
    hostname: eurekaC
  client:
    register-with-eureka: true # 是否将自己注册到Eureka-Server中
    fetch-registry: true # 是否从Eureka-Server中获取服务注册信息
    service-url:
      defaultZone: http://192.168.3.8:9000/eureka/,http://192.168.3.8:9001/eureka/